// data.jsx — Inhalte für Autohaus Fischer

const TEAM = [
  { name: 'Franz Fischer',     role: 'Inhaber, Gründer',         initials: 'FF', tone: 'sand', gen: '1. Generation' },
  { name: 'Monika Fischer',    role: 'Inhaberin, Gründerin',     initials: 'MF', tone: 'rose', gen: '1. Generation' },
  { name: 'Marko Fischer',     role: 'Geschäftsleitung',         initials: 'M',  tone: 'ink',  gen: '2. Generation' },
  { name: 'Irina Fischer',     role: 'Inhaberin',                initials: 'I',  tone: 'warm', gen: '2. Generation' },
  { name: 'Daniel Fischer',    role: 'Stv. Geschäftsführer',     initials: 'D',  tone: 'cool', gen: '3. Generation' },
  { name: 'David Balogh',      role: 'Verkaufsleitung',          initials: 'DB', tone: 'sage' },
  { name: 'Marion Schulz',     role: 'Service & Annahme',        initials: 'MS', tone: 'fog' },
  { name: 'Bojan Benko',       role: 'Teile & Garantie',         initials: 'BB', tone: 'moss' },
  { name: 'Robert Scholz',     role: 'Verkauf',                  initials: 'RS', tone: 'sand' },
  { name: 'Philipp Scholz',    role: 'Annahme & Teile',          initials: 'PS', tone: 'cool' },
  { name: 'Maximilian Pajones',role: 'Fahrzeugtechnik',          initials: 'MP', tone: 'moss' },
  { name: 'Kristian Stevanovic',role:'Fahrzeugtechnik',          initials: 'KS', tone: 'sage' },
];

const CARS = [
  {
    id: 'ioniq5',
    name: 'Hyundai Ioniq 5',
    variant: 'Long Range AWD · 2024',
    year: '2024',
    km: '3.200',
    color: 'Anthrazit',
    fuel: 'Elektro',
    transmission: 'Automatik',
    power: '239 kW / 325 PS',
    price: '€ 41.200',
    rate: '€ 389 / Monat',
    tag: { label: 'Neu im Bestand', cls: 'accent' },
    img: { tone: 'slate', model: 'suv', plate: 'W' },
    badge: 'Elektro',
    dealer: 0, // index in TEAM (David Balogh → fix)
  },
  {
    id: 'kona',
    name: 'Hyundai Kona Elektro',
    variant: '64 kWh Trend · 2024',
    year: '2024',
    km: '8.500',
    color: 'Atlas White',
    fuel: 'Elektro',
    transmission: 'Automatik',
    power: '150 kW / 204 PS',
    price: '€ 28.900',
    rate: '€ 269 / Monat',
    tag: { label: 'Probefahrt', cls: 'electric' },
    img: { tone: 'mist', model: 'suv', plate: 'EL' },
    badge: 'Elektro',
    dealer: 0,
  },
  {
    id: 'tucson',
    name: 'Hyundai Tucson Hybrid',
    variant: 'N Line · 2023',
    year: '2023',
    km: '21.400',
    color: 'Phantom Black',
    fuel: 'Hybrid',
    transmission: 'Automatik',
    power: '169 kW / 230 PS',
    price: '€ 32.500',
    rate: '€ 305 / Monat',
    tag: null,
    img: { tone: 'beige', model: 'suv', plate: '' },
    badge: 'Hybrid',
    dealer: 0,
  },
  {
    id: 'eclipse',
    name: 'Mitsubishi Eclipse Cross',
    variant: 'PHEV Diamond · 2024',
    year: '2024',
    km: '6.100',
    color: 'Sterling Silver',
    fuel: 'Plug-in Hybrid',
    transmission: 'Automatik',
    power: '138 kW / 188 PS',
    price: '€ 26.800',
    rate: '€ 249 / Monat',
    tag: { label: 'Ausstellung', cls: '' },
    img: { tone: 'mist', model: 'suv', plate: '' },
    badge: 'PHEV',
    dealer: 0,
  },
  {
    id: 'i30',
    name: 'Hyundai i30 Kombi',
    variant: '1.5 T-GDI 48V · 2022',
    year: '2022',
    km: '38.900',
    color: 'Intense Blue',
    fuel: 'Mild Hybrid',
    transmission: 'Manuell',
    power: '117 kW / 160 PS',
    price: '€ 18.400',
    rate: '€ 179 / Monat',
    tag: { label: 'Eintauschwagen', cls: '' },
    img: { tone: 'slate', model: 'kombi', plate: '' },
    badge: 'Kombi',
    dealer: 0,
  },
  {
    id: 'asx',
    name: 'Mitsubishi ASX',
    variant: '1.6 Diamond · 2024',
    year: '2024',
    km: '2.100',
    color: 'Granitschwarz',
    fuel: 'Benzin',
    transmission: 'Automatik',
    power: '116 kW / 158 PS',
    price: '€ 24.500',
    rate: '€ 229 / Monat',
    tag: { label: 'Lagernd', cls: '' },
    img: { tone: 'forest', model: 'suv', plate: '' },
    badge: 'Neuwagen',
    dealer: 0,
  },
  {
    id: 'spacestar',
    name: 'Mitsubishi Space Star',
    variant: 'Invite+ · 2023',
    year: '2023',
    km: '12.700',
    color: 'Sunrise Red',
    fuel: 'Benzin',
    transmission: 'Manuell',
    power: '52 kW / 71 PS',
    price: '€ 14.900',
    rate: '€ 149 / Monat',
    tag: null,
    img: { tone: 'rouge', model: 'sedan', plate: '' },
    badge: 'Stadtauto',
    dealer: 0,
  },
  {
    id: 'i20',
    name: 'Hyundai i20',
    variant: 'Trend Line · 2023',
    year: '2023',
    km: '15.300',
    color: 'Lumen Gray',
    fuel: 'Benzin',
    transmission: 'Manuell',
    power: '74 kW / 100 PS',
    price: '€ 17.200',
    rate: '€ 169 / Monat',
    tag: null,
    img: { tone: 'mist', model: 'sedan', plate: '' },
    badge: 'Stadtauto',
    dealer: 0,
  },
];

const SERVICES = [
  { t: 'Neuwagen',     d: 'Hyundai & Mitsubishi · konfigurieren oder lagernd' },
  { t: 'Eintausch',    d: 'Mit Garantie & Überprüfung · faire Bewertung im Haus' },
  { t: 'Werkstatt',    d: 'Service · §57a · Karosserie · Havariedienst' },
  { t: 'Finanzierung', d: 'Leasing, Versicherung & Beratung — am Tisch geklärt' },
  { t: 'Ersatzwagen',  d: 'Während Service & Havarie · ohne Aufpreis' },
  { t: 'Reifen',       d: 'Wechsel, Service, Einlagerung in unserem Lager' },
];

const WERKSTATT_TYPES = [
  { ti: 'Service / §57a', du: '2–3 Stunden' },
  { ti: 'Reifenwechsel',  du: '45 Minuten' },
  { ti: 'Inspektion',     du: '3–5 Stunden' },
  { ti: 'Karosserie',     du: 'Auf Anfrage' },
];

const TESTIMONIALS = [
  {
    quote: 'Bei den Fischers fühlt man sich nicht wie ein Kunde, sondern wie ein Nachbar.',
    who: 'Helga K.',
    detail: 'Kundin seit 1995 · 1220 Wien',
  },
  {
    quote: 'Drei Generationen unter einem Dach — bei Reparaturen redet man mit jemandem, der den Wagen kennt.',
    who: 'Andreas S.',
    detail: 'Stammkunde · Donaustadt',
  },
  {
    quote: 'Ehrliche Beratung, faires Eintausch-Angebot, kein Verkaufsdruck. Selten geworden.',
    who: 'Familie Pichler',
    detail: 'Drittes Auto vom Fischer · 2024',
  },
];

Object.assign(window, { TEAM, CARS, SERVICES, WERKSTATT_TYPES, TESTIMONIALS });
