// AUTO-GENERATED by scripts/fetch-cars.ts — re-run `npm run fetch:cars` to refresh.

export type Gradient =
  | "hero-teal"
  | "hero-cream"
  | "hero-blush"
  | "hero-sage"
  | "hero-sky"
  | "hero-slate";

export type Brand = "Ferrari" | "Porsche" | "BMW" | "Sonstige";

export type VehicleSpecs = {
  year: string | null;
  mileage: string | null;
  horsepower: string | null;
  transmission: string | null;
  color: string | null;
};

export type Vehicle = {
  num: string;
  slug: string;
  brand: Brand;
  name: string;
  subtitle: string;
  gradient: Gradient;
  src: string;
  srcAvif: string;
  srcHover?: string;
  blurDataURL: string;
  width: number;
  height: number;
  alt: string;
  highlight?: string;
  specs: VehicleSpecs;
};

export const vehicles: Vehicle[] = [
  {
    "num": "01",
    "slug": "ferrari-488-spider",
    "brand": "Ferrari",
    "name": "Ferrari 488",
    "subtitle": "Spider",
    "gradient": "hero-blush",
    "src": "/cars/ferarri-red8.png",
    "srcAvif": "/cars/ferarri-red8.png",
    "srcHover": "/cars/ferarri3.png",
    "blurDataURL": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAACqADAAQAAAABAAAACAAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgACAAKAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMACQkJCQkJEAkJEBYQEBAWHhYWFhYeJh4eHh4eJi4mJiYmJiYuLi4uLi4uLjc3Nzc3N0BAQEBASEhISEhISEhISP/bAEMBCwwMEhESHxERH0szKjNLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS//dAAQAAf/aAAwDAQACEQMRAD8AuXepa39pNvZ2yJGrYDkqQRnryc/pWzF5zRK0oi3kDdgnGe9VX71OOgqbeZ0Od0rRR//Z",
    "width": 1448,
    "height": 1086,
    "alt": "Ferrari 488 Spider, Seitenansicht",
    "highlight": "Aus Privatsammlung · Erstbesitz",
    "specs": {
      "year": "2018",
      "mileage": "12.400 km",
      "horsepower": "670 PS",
      "transmission": "F1-Doppelkupplung",
      "color": "Rosso Corsa"
    }
  },
  {
    "num": "02",
    "slug": "ferrari-488-pista",
    "brand": "Ferrari",
    "name": "Ferrari 488",
    "subtitle": "Pista",
    "gradient": "hero-blush",
    "src": "/cars/nicke5.png",
    "srcAvif": "/cars/nicke5.png",
    "srcHover": "/cars/nicke2.png",
    "blurDataURL": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAACqADAAQAAAABAAAACAAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgACAAKAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMACQkJCQkJEAkJEBYQEBAWHhYWFhYeJh4eHh4eJi4mJiYmJiYuLi4uLi4uLjc3Nzc3N0BAQEBASEhISEhISEhISP/bAEMBCwwMEhESHxERH0szKjNLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS//dAAQAAf/aAAwDAQACEQMRAD8A2J9b14SC20u0jjiVsF3wQ49euR+VaaSoUUzrGJCBu29N3fHtmq0X3R9ahb7x+tSl5mznorJH/9k=",
    "width": 1448,
    "height": 1086,
    "alt": "Ferrari 488 Pista, Seitenansicht",
    "highlight": "Limitiert · Werkscarbon-Paket",
    "specs": {
      "year": "2019",
      "mileage": "6.800 km",
      "horsepower": "720 PS",
      "transmission": "F1-Doppelkupplung",
      "color": "Rosso Corsa"
    }
  },
  {
    "num": "03",
    "slug": "ferrari-458-speciale-aperta",
    "brand": "Ferrari",
    "name": "Ferrari 458",
    "subtitle": "Speciale Aperta",
    "gradient": "hero-cream",
    "src": "/cars/ferarri-gelb6.png",
    "srcAvif": "/cars/ferarri-gelb6.png",
    "srcHover": "/cars/ferarri-gelb2.png",
    "blurDataURL": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAACqADAAQAAAABAAAACAAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgACAAKAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMACQkJCQkJEAkJEBYQEBAWHhYWFhYeJh4eHh4eJi4mJiYmJiYuLi4uLi4uLjc3Nzc3N0BAQEBASEhISEhISEhISP/bAEMBCwwMEhESHxERH0szKjNLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS//dAAQAAf/aAAwDAQACEQMRAD8A6Oa6vFnFvb2rYVgrMVBBBPUHcKuCGdhuMSgnnG7pV4/6z8RTz1rFJ3epppbY/9k=",
    "width": 1448,
    "height": 1086,
    "alt": "Ferrari 458 Speciale Aperta, Seitenansicht",
    "highlight": "499 Stück weltweit · Investment",
    "specs": {
      "year": "2015",
      "mileage": "9.200 km",
      "horsepower": "605 PS",
      "transmission": "F1-Doppelkupplung",
      "color": "Giallo Modena"
    }
  },
  {
    "num": "04",
    "slug": "porsche-718-spyder-4-0",
    "brand": "Porsche",
    "name": "Porsche 718",
    "subtitle": "Spyder 4.0",
    "gradient": "hero-sky",
    "src": "/cars/blau3.png",
    "srcAvif": "/cars/blau3.png",
    "srcHover": "/cars/blau2.png",
    "blurDataURL": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAACqADAAQAAAABAAAACAAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgACAAKAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMACQkJCQkJEAkJEBYQEBAWHhYWFhYeJh4eHh4eJi4mJiYmJiYuLi4uLi4uLjc3Nzc3N0BAQEBASEhISEhISEhISP/bAEMBCwwMEhESHxERH0szKjNLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS//dAAQAAf/aAAwDAQACEQMRAD8AS7v9ZSc2tnapHGjY3madw98nj8K6eFY3iR5YUDlQWAbgEjms65/1kn1rQT7g+lat+Qkj/9k=",
    "width": 1448,
    "height": 1086,
    "alt": "Porsche 718 Spyder 4.0, Seitenansicht",
    "highlight": "Manueller GT4-Antrieb",
    "specs": {
      "year": "2021",
      "mileage": "11.500 km",
      "horsepower": "420 PS",
      "transmission": "6-Gang manuell",
      "color": "Saphirblau Metallic"
    }
  },
  {
    "num": "05",
    "slug": "bmw-z3-m-coupe-s54",
    "brand": "BMW",
    "name": "BMW Z3",
    "subtitle": "M Coupé S54",
    "gradient": "hero-slate",
    "src": "/cars/grau1.png",
    "srcAvif": "/cars/grau1.png",
    "srcHover": "/cars/grau2.png",
    "blurDataURL": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAACqADAAQAAAABAAAACAAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgACAAKAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMACQkJCQkJEAkJEBYQEBAWHhYWFhYeJh4eHh4eJi4mJiYmJiYuLi4uLi4uLjc3Nzc3N0BAQEBASEhISEhISEhISP/bAEMBCwwMEhESHxERH0szKjNLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS//dAAQAAf/aAAwDAQACEQMRAD8A6ye/vv8AVWkIRQT85KkEY461ZWeIqDIoDY5weM++4gH+rFVT1NMD/2Q==",
    "width": 1448,
    "height": 1086,
    "alt": "BMW Z3 M Coupé S54, Seitenansicht",
    "highlight": "Kultstatus · S54 Motor",
    "specs": {
      "year": "2002",
      "mileage": "62.500 km",
      "horsepower": "325 PS",
      "transmission": "5-Gang manuell",
      "color": "Titansilber Metallic"
    }
  }
];

export function getVehicle(slug: string): Vehicle | undefined {
  return vehicles.find((v) => v.slug === slug);
}

export function getVehicleSlugs(): string[] {
  return vehicles.map((v) => v.slug);
}
