// AUTO-GENERATED by scripts/fetch-cars.ts — re-run `npm run fetch:cars` to refresh.
//
// TODO: the numeric fields (priceEur, horsepowerPs, mileageKm, yearNum) below
// are hand-maintained. `scripts/fetch-cars.ts` does NOT emit them yet; it must
// be taught to parse them from the corresponding display strings before the
// next regeneration, otherwise these values will be wiped.

export type Gradient =
  | "hero-teal"
  | "hero-cream"
  | "hero-blush"
  | "hero-sage"
  | "hero-sky"
  | "hero-slate";

export type Brand = "Ferrari" | "Porsche" | "BMW" | "Sonstige";

export type VehicleSpecs = {
  year: string | null;
  mileage: string | null;
  horsepower: string | null;
  transmission: string | null;
  color: string | null;
};

export type Vehicle = {
  num: string;
  slug: string;
  brand: Brand;
  name: string;
  subtitle: string;
  gradient: Gradient;
  src: string;
  srcAvif: string;
  srcHover?: string;
  blurDataURL: string;
  width: number;
  height: number;
  alt: string;
  highlight?: string;
  price?: string;
  category?: string;
  /** Numeric companions for range filters — parsed from display strings. */
  priceEur?: number | null;
  horsepowerPs?: number | null;
  mileageKm?: number | null;
  yearNum?: number | null;
  specs: VehicleSpecs;
  gallery: string[];
};

export const vehicles: Vehicle[] = [
  {
    "num": "01",
    "slug": "ferrari-488-spider",
    "brand": "Ferrari",
    "name": "Ferrari 488",
    "subtitle": "Spider",
    "gradient": "hero-blush",
    "src": "/cars/ferarri-red8.png",
    "srcAvif": "/cars/ferarri-red8.png",
    "srcHover": "/cars/ferarri3.png",
    "blurDataURL": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAACqADAAQAAAABAAAACAAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgACAAKAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMACQkJCQkJEAkJEBYQEBAWHhYWFhYeJh4eHh4eJi4mJiYmJiYuLi4uLi4uLjc3Nzc3N0BAQEBASEhISEhISEhISP/bAEMBCwwMEhESHxERH0szKjNLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS//dAAQAAf/aAAwDAQACEQMRAD8AuXepa39pNvZ2yJGrYDkqQRnryc/pWzF5zRK0oi3kDdgnGe9VX71OOgqbeZ0Od0rRR//Z",
    "width": 1448,
    "height": 1086,
    "alt": "Ferrari 488 Spider, Seitenansicht",
    "highlight": "Erstbesitz",
    "price": "€ 189.900,-",
    "category": "Sammlerfahrzeug",
    "priceEur": 189900,
    "horsepowerPs": 670,
    "mileageKm": 12400,
    "yearNum": 2018,
    "specs": {
      "year": "2018",
      "mileage": "12.400 km",
      "horsepower": "670 PS",
      "transmission": "F1-Doppelkupplung",
      "color": "Rosso Corsa"
    },
    "gallery": [
      "/cars/ferarri-red3.png",
      "/cars/ferarri-red4.png",
      "/cars/ferarri-red6.png",
      "/cars/ferarri-red8.png"
    ]
  },
  {
    "num": "02",
    "slug": "ferrari-488-pista",
    "brand": "Ferrari",
    "name": "Ferrari 488",
    "subtitle": "Pista",
    "gradient": "hero-blush",
    "src": "/cars/nicke5.png",
    "srcAvif": "/cars/nicke5.png",
    "srcHover": "/cars/nicke2.png",
    "blurDataURL": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAACqADAAQAAAABAAAACAAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgACAAKAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMACQkJCQkJEAkJEBYQEBAWHhYWFhYeJh4eHh4eJi4mJiYmJiYuLi4uLi4uLjc3Nzc3N0BAQEBASEhISEhISEhISP/bAEMBCwwMEhESHxERH0szKjNLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS//dAAQAAf/aAAwDAQACEQMRAD8A2J9b14SC20u0jjiVsF3wQ49euR+VaaSoUUzrGJCBu29N3fHtmq0X3R9ahb7x+tSl5mznorJH/9k=",
    "width": 1448,
    "height": 1086,
    "alt": "Ferrari 488 Pista, Seitenansicht",
    "highlight": "Werkscarbon-Paket",
    "price": "€ 389.900,-",
    "category": "Sammlerfahrzeug",
    "priceEur": 389900,
    "horsepowerPs": 720,
    "mileageKm": 6800,
    "yearNum": 2019,
    "specs": {
      "year": "2019",
      "mileage": "6.800 km",
      "horsepower": "720 PS",
      "transmission": "F1-Doppelkupplung",
      "color": "Rosso Corsa"
    },
    "gallery": [
      "/cars/nicke1.png",
      "/cars/nicke2.png",
      "/cars/nicke3.png",
      "/cars/nicke4.png",
      "/cars/nicke5.png"
    ]
  },
  {
    "num": "03",
    "slug": "ferrari-458-speciale-aperta",
    "brand": "Ferrari",
    "name": "Ferrari 458",
    "subtitle": "Speciale Aperta",
    "gradient": "hero-cream",
    "src": "/cars/ferarri-gelb6.png",
    "srcAvif": "/cars/ferarri-gelb6.png",
    "srcHover": "/cars/ferarri-gelb2.png",
    "blurDataURL": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAACqADAAQAAAABAAAACAAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgACAAKAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMACQkJCQkJEAkJEBYQEBAWHhYWFhYeJh4eHh4eJi4mJiYmJiYuLi4uLi4uLjc3Nzc3N0BAQEBASEhISEhISEhISP/bAEMBCwwMEhESHxERH0szKjNLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS//dAAQAAf/aAAwDAQACEQMRAD8A6Oa6vFnFvb2rYVgrMVBBBPUHcKuCGdhuMSgnnG7pV4/6z8RTz1rFJ3epppbY/9k=",
    "width": 1448,
    "height": 1086,
    "alt": "Ferrari 458 Speciale Aperta, Seitenansicht",
    "highlight": "499 Stück weltweit",
    "price": "€ 549.900,-",
    "category": "Sondermodell",
    "priceEur": 549900,
    "horsepowerPs": 605,
    "mileageKm": 9200,
    "yearNum": 2015,
    "specs": {
      "year": "2015",
      "mileage": "9.200 km",
      "horsepower": "605 PS",
      "transmission": "F1-Doppelkupplung",
      "color": "Giallo Modena"
    },
    "gallery": [
      "/cars/ferarri-gelb1.png",
      "/cars/ferarri-gelb2.png",
      "/cars/ferarri-gelb3.png",
      "/cars/ferarri-gelb4.png",
      "/cars/ferarri-gelb6.png",
      "/cars/ferarri-gelb7.png"
    ]
  },
  {
    "num": "04",
    "slug": "porsche-718-spyder-4-0",
    "brand": "Porsche",
    "name": "Porsche 718",
    "subtitle": "Spyder 4.0",
    "gradient": "hero-sky",
    "src": "/cars/blau3.png",
    "srcAvif": "/cars/blau3.png",
    "srcHover": "/cars/blau2.png",
    "blurDataURL": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAACqADAAQAAAABAAAACAAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgACAAKAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMACQkJCQkJEAkJEBYQEBAWHhYWFhYeJh4eHh4eJi4mJiYmJiYuLi4uLi4uLjc3Nzc3N0BAQEBASEhISEhISEhISP/bAEMBCwwMEhESHxERH0szKjNLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS//dAAQAAf/aAAwDAQACEQMRAD8AS7v9ZSc2tnapHGjY3madw98nj8K6eFY3iR5YUDlQWAbgEjms65/1kn1rQT7g+lat+Qkj/9k=",
    "width": 1448,
    "height": 1086,
    "alt": "Porsche 718 Spyder 4.0, Seitenansicht",
    "highlight": "Manueller GT4-Antrieb",
    "price": "€ 129.900,-",
    "category": "Gebrauchtwagen",
    "priceEur": 129900,
    "horsepowerPs": 420,
    "mileageKm": 11500,
    "yearNum": 2021,
    "specs": {
      "year": "2021",
      "mileage": "11.500 km",
      "horsepower": "420 PS",
      "transmission": "6-Gang manuell",
      "color": "Saphirblau Metallic"
    },
    "gallery": [
      "/cars/blau1.png",
      "/cars/blau2.png",
      "/cars/blau3.png",
      "/cars/blau4.png",
      "/cars/blau5.png"
    ]
  },
  {
    "num": "05",
    "slug": "bmw-z3-m-coupe-s54",
    "brand": "BMW",
    "name": "BMW Z3",
    "subtitle": "M Coupé S54",
    "gradient": "hero-slate",
    "src": "/cars/grau1.png",
    "srcAvif": "/cars/grau1.png",
    "srcHover": "/cars/grau2.png",
    "blurDataURL": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAACqADAAQAAAABAAAACAAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgACAAKAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMACQkJCQkJEAkJEBYQEBAWHhYWFhYeJh4eHh4eJi4mJiYmJiYuLi4uLi4uLjc3Nzc3N0BAQEBASEhISEhISEhISP/bAEMBCwwMEhESHxERH0szKjNLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS//dAAQAAf/aAAwDAQACEQMRAD8A6ye/vv8AVWkIRQT85KkEY461ZWeIqDIoDY5weM++4gH+rFVT1NMD/2Q==",
    "width": 1448,
    "height": 1086,
    "alt": "BMW Z3 M Coupé S54, Seitenansicht",
    "highlight": "Kultstatus · S54 Motor",
    "price": "€ 74.900,-",
    "category": "Klassiker",
    "priceEur": 74900,
    "horsepowerPs": 325,
    "mileageKm": 62500,
    "yearNum": 2002,
    "specs": {
      "year": "2002",
      "mileage": "62.500 km",
      "horsepower": "325 PS",
      "transmission": "5-Gang manuell",
      "color": "Titansilber Metallic"
    },
    "gallery": [
      "/cars/grau1.png",
      "/cars/grau2.png",
      "/cars/grau3.png",
      "/cars/grau4.png",
      "/cars/grau5.png",
      "/cars/grau6.png"
    ]
  }
];

export function getVehicle(slug: string): Vehicle | undefined {
  return vehicles.find((v) => v.slug === slug);
}

export function getVehicleSlugs(): string[] {
  return vehicles.map((v) => v.slug);
}
