// AUTO-GENERATED by scripts/fetch-cars.ts — re-run `npm run fetch:cars` to refresh.

export type Gradient =
  | "hero-teal"
  | "hero-cream"
  | "hero-blush"
  | "hero-sage"
  | "hero-sky"
  | "hero-slate";

export type Brand = "Ferrari" | "Porsche" | "BMW" | "Sonstige";

export type VehicleSpecs = {
  year: string | null;
  mileage: string | null;
  horsepower: string | null;
  transmission: string | null;
  color: string | null;
};

export type Vehicle = {
  num: string;
  slug: string;
  brand: Brand;
  name: string;
  subtitle: string;
  gradient: Gradient;
  src: string;
  srcAvif: string;
  blurDataURL: string;
  width: number;
  height: number;
  alt: string;
  specs: VehicleSpecs;
};

export const vehicles: Vehicle[] = [
  {
    "num": "01",
    "slug": "ferrari-488-spider",
    "brand": "Ferrari",
    "name": "Ferrari 488",
    "subtitle": "Spider",
    "gradient": "hero-blush",
    "src": "/cars/ferrari-488-spider.jpg",
    "srcAvif": "/cars/ferrari-488-spider.avif",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgEE/8QAHxAAAgICAgMBAAAAAAAAAAAAAQIDEQAEITEFElGR/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwDS2rtEI2u8QRgD3zf5kmDwMEd1LVZrq8C+SaCo3QNXVcYHneZvdqF/BhTH/9k=",
    "width": 793,
    "height": 946,
    "alt": "Ferrari 488 Spider, Seitenansicht",
    "specs": {
      "year": null,
      "mileage": null,
      "horsepower": null,
      "transmission": null,
      "color": null
    }
  },
  {
    "num": "02",
    "slug": "ferrari-488-pista",
    "brand": "Ferrari",
    "name": "Ferrari 488",
    "subtitle": "Pista",
    "gradient": "hero-sage",
    "src": "/cars/ferrari-488-pista.jpg",
    "srcAvif": "/cars/ferrari-488-pista.avif",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQAE/8QAIxAAAgEDAwQDAAAAAAAAAAAAAQIDAAQREiEiBRNBUXGx4f/EABUBAQEAAAAAAAAAAAAAAAAAAAED/8QAGREAAgMBAAAAAAAAAAAAAAAAAREAAgMT/9oADAMBAAIRAxEAPwCfqUaT9p0jD+eR+8VqDSkbW8ZHsSflENBdRyvE9q8q52ZTt80jbJOI+YEZJzp1ZxR0s1KHOiYM/9k=",
    "width": 709,
    "height": 945,
    "alt": "Ferrari 488 Pista, Seitenansicht",
    "specs": {
      "year": null,
      "mileage": null,
      "horsepower": null,
      "transmission": null,
      "color": null
    }
  },
  {
    "num": "03",
    "slug": "ferrari-458-speciale-aperta",
    "brand": "Ferrari",
    "name": "Ferrari 458",
    "subtitle": "Speciale Aperta",
    "gradient": "hero-blush",
    "src": "/cars/ferrari-458-speciale-aperta.jpg",
    "srcAvif": "/cars/ferrari-458-speciale-aperta.avif",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJAAwDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwT/xAAfEAACAgEEAwAAAAAAAAAAAAABAgADERIhM0FxcoH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABcRAQADAAAAAAAAAAAAAAAAAAEAAhH/2gAMAwEAAhEDEQA/AGK1tSSL61KoWbSAcAdbmGrOyIagMaRu4wc/JJZzD2lw78ya0ddYrP/Z",
    "width": 1261,
    "height": 946,
    "alt": "Ferrari 458 Speciale Aperta, Seitenansicht",
    "specs": {
      "year": null,
      "mileage": null,
      "horsepower": null,
      "transmission": null,
      "color": null
    }
  },
  {
    "num": "04",
    "slug": "porsche-718-spyder-4-0",
    "brand": "Porsche",
    "name": "Porsche 718",
    "subtitle": "Spyder 4.0",
    "gradient": "hero-sky",
    "src": "/cars/porsche-718-spyder-4-0.jpg",
    "srcAvif": "/cars/porsche-718-spyder-4-0.avif",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJAAwDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQIEBf/EACIQAAEDAwMFAAAAAAAAAAAAAAIAAQMEERIFMTIhQmFxkf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFxEBAAMAAAAAAAAAAAAAAAAAABESYf/aAAwDAQACEQMRAD8ALauDwFlFEPTuN2u3xLTVIRU8cYRhYWtfPfzssmu5RKkeLelOunL/2Q==",
    "width": 1261,
    "height": 946,
    "alt": "Porsche 718 Spyder 4.0, Seitenansicht",
    "specs": {
      "year": null,
      "mileage": null,
      "horsepower": null,
      "transmission": null,
      "color": null
    }
  },
  {
    "num": "05",
    "slug": "porsche-cayman-r-peridotmetallic",
    "brand": "Porsche",
    "name": "Porsche Cayman",
    "subtitle": "\"R\" Peridotmetallic",
    "gradient": "hero-sage",
    "src": "/cars/porsche-cayman-r-peridotmetallic.jpg",
    "srcAvif": "/cars/porsche-cayman-r-peridotmetallic.avif",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAIAAwDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAL/xAAeEAABBAMAAwAAAAAAAAAAAAABAAIDEQQSITFhkf/EABUBAQEAAAAAAAAAAAAAAAAAAAED/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAERAzH/2gAMAwEAAhEDEQA/ALZkakCSTV/RqBwe7RuTK+yJGAXXki/qIprNWA9X2I//2Q==",
    "width": 1400,
    "height": 887,
    "alt": "Porsche Cayman \"R\" Peridotmetallic, Seitenansicht",
    "specs": {
      "year": null,
      "mileage": null,
      "horsepower": null,
      "transmission": null,
      "color": null
    }
  },
  {
    "num": "06",
    "slug": "porsche-996-gt3-rs",
    "brand": "Porsche",
    "name": "Porsche 996",
    "subtitle": "GT3 RS",
    "gradient": "hero-slate",
    "src": "/cars/porsche-996-gt3-rs.jpg",
    "srcAvif": "/cars/porsche-996-gt3-rs.avif",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwQF/8QAIhAAAQIFBAMAAAAAAAAAAAAAAQIDAAQRIXEFEhM0IoHB/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABcRAAMBAAAAAAAAAAAAAAAAAAABEgL/2gAMAwEAAhEDEQA/AFmn0lpO+Zc5XPEIQgLGKG8ANMmVpHCk7QKXtX1eLJbtPYjYlOsjH2By6Gak/9k=",
    "width": 1279,
    "height": 945,
    "alt": "Porsche 996 GT3 RS, Seitenansicht",
    "specs": {
      "year": null,
      "mileage": null,
      "horsepower": null,
      "transmission": null,
      "color": null
    }
  },
  {
    "num": "07",
    "slug": "bmw-z3-m-coupe-s54",
    "brand": "BMW",
    "name": "BMW Z3",
    "subtitle": "M Coupé S54",
    "gradient": "hero-cream",
    "src": "/cars/bmw-z3-m-coupe-s54.jpg",
    "srcAvif": "/cars/bmw-z3-m-coupe-s54.avif",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAIAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEE/8QAHhABAAEEAgMAAAAAAAAAAAAAAQIAAwQhERMiMWH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAExQf/aAAwDAQACEQMRAD8AmXccO91Q8tCKO/fJqtscZlCKkdgg8ifKUoOIWn//2Q==",
    "width": 1381,
    "height": 946,
    "alt": "BMW Z3 M Coupé S54, Seitenansicht",
    "specs": {
      "year": null,
      "mileage": null,
      "horsepower": null,
      "transmission": null,
      "color": null
    }
  }
];

export function getVehicle(slug: string): Vehicle | undefined {
  return vehicles.find((v) => v.slug === slug);
}

export function getVehicleSlugs(): string[] {
  return vehicles.map((v) => v.slug);
}
